# Generated by Django 2.1.4 on 2019-01-16 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gongdantest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditprocess',
            name='audituser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审批用户'),
        ),
    ]
