# Generated by Django 2.1.4 on 2019-01-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongdantest', '0002_auto_20190116_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.IntegerField(verbose_name='工单ID')),
                ('username', models.CharField(max_length=100, verbose_name='创建用户')),
                ('caseinfo', models.TextField(verbose_name='工单内容')),
            ],
        ),
    ]
