# Generated by Django 2.1.4 on 2019-01-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongdantest', '0003_usercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercase',
            name='casename',
            field=models.CharField(default=1, max_length=100, verbose_name='工单名称'),
            preserve_default=False,
        ),
    ]
