# Generated by Django 2.1.4 on 2019-01-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongdantest', '0004_usercase_casename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercase',
            name='id',
        ),
        migrations.AlterField(
            model_name='usercase',
            name='caseid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
