# Generated by Django 2.1.4 on 2019-01-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongdantest', '0006_usercase_workflowid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecodr',
            name='current',
            field=models.IntegerField(default=3, verbose_name='当前审批阶段'),
            preserve_default=False,
        ),
    ]
