# Generated by Django 2.1.4 on 2019-01-17 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongdantest', '0008_auditrecodr_auditcontents'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercase',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
