# Generated by Django 2.1.4 on 2019-01-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongdantest', '0010_auditrecodr_rejectflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercase',
            name='rejectflag',
            field=models.IntegerField(default=0, verbose_name='是否驳回'),
        ),
    ]
